.Dd $Mdocdate: October 16 2016 $
.Dt IOMENU 1
.Os
.Sh NAME
.Nm iomenu
.Op Fl nNHksl
.
.
.Sh DESCRIPTION
.
The
.Nm
utility filters lines form stdin interactively with the keyboard, and print
the selected line to stdout.
.Pp
Lower case switches are for the interface, uppercase switches are for
input/output.
.Bl -tag
.It Fl n
Display line numbers in interface.
.
.It Fl N
Return the line number rather than the match.
.
.It Fl H
Return the current header that the selection belongs to in addition to the
match, delimited by a tab.
.
.It Fl k Cm key
Key to use to validate current selection in addition to Enter.
.
.It Fl s Cm separator
Character separating the content from the comments.  Every character after
the separator will be considered as comment and will be grayed and aligned
in the interface.
.Pp
If a separator is at the beginning of a line (without leading space), the
line is considered as a section header, and it will always be displayed
regardless if it matches or not.
.
.It Fl l Cm lines
Number of lines to display at once.  Default is 30.
.El
.
.
.Sh KEYBINDINGS
.
.Bl -tag
.It Cm ^M, ^J, Enter
Print the matched line to stdout and exit.
.
.It Cm ^@, ^Space
Print the content of the input rather than the matched line to stdout and exit.
.
.It Cm ^P / ^N, Up / Down
Navigate to the previous / next line.
.
.It Cm PageUp / PageDown
Navigate 10 lines up / down.
.
.It Cm ^I, Tab
Set input to the currently highlighted candidate, then cycle through candidate
list.
.
.It Cm ^H, Backspace
Delete one char backward, but if there is no char
backward, it should return an error code of 1.
.
.It Cm ^C
Cancel, and make filter return the error code of 1.
.
.It Cm ^W
Deletes the last entered word.
.
.It Cm ^U
Deletes the entire input and jump to the first line.
.El
