int		 utf8_runelen	(long);
int		 utf8_utflen	(char const *);
long		 utf8_torune	(char const **);
int		 utf8_tostr	(char *, long);
int		 utf8_isprint	(long);
int		 utf8_wcwidth	(long);
int		 utf8_runewidth	(long, size_t);
int		 utf8_col	(char const *, size_t, size_t);
int		 utf8_putrune	(long, int, int, FILE *);
char const	*utf8_nextrune	(char const *);
char const	*utf8_prevrune	(char const *);
